language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
  
 notifications:
  slack: 'sytw:GgiUiOJJeifKY0uamYUGF1Zr#12'
  travis encrypt "sytw:GgiUiOJJeifKY0uamYUGF1Zr#12" --add notifications.slack.rooms
  
